name: Playwright
description: Runs Playwright e2e tests

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js 23.11.0
      uses: actions/setup-node@v4
      with:
        node-version: 23.11.0
        check-latest: true

    - name: Cache pnpm modules
      uses: actions/cache@v4
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - uses: actions/cache@v4
      with:
        path: |
          ~/.pnpm-store
          ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
            
    - uses: pnpm/action-setup@v3
      with:
        version: 8.6.11
        run_install: true

    - name: Install playwright
      run: pnpm playwright:install
      shell: bash

    - name: Run playwright tests
      run: pnpm playwright:ci
      shell: bash
      env:
        TZ: Europe/Madrid

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 7
